on: [ pull_request ]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.16.x ]
        os: [ macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go test ./...  -coverprofile fmtcoverage.html fmt
      - name: Coverage badge
        run: bash <(curl -s https://codecov.io/bash)
